style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/Placidina/terraform-aws-efs
options:
  header:
    pattern: "^(.*)$"
    pattern_maps:
      - Subject
